version: "3.8"

services:
  mongodb:
    build:
      context: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: parking
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017

    ports:
      - 27017:27017
